### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by notthetup** [notthetup/soundboard#1]
```
Still playing.. 0
Playing... sounds/music/shinyspaceships_intro_outro_trimmed.wav
Fading In..  37
buffer.js:1009
    throw new TypeError('value is out of bounds');
    ^

TypeError: value is out of bounds
    at checkInt (buffer.js:1009:11)
    at Buffer.writeInt16LE (buffer.js:1177:5)
    at Mixer.<anonymous> (/Users/chinmay/Documents/Personal/Projects/soundboard/node_modules/audio-mixer/lib/mixer.js:79:22)
    at Array.forEach (native)
    at Mixer._read (/Users/chinmay/Documents/Personal/Projects/soundboard/node_modules/audio-mixer/lib/mixer.js:72:15)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/chinmay/.nvm/versions/node/v5.12.0/bin/node" "/Users/chinmay/.nvm/versions/node/v5.12.0/bin/npm" "start"
```

**Comment by notthetup** [comment]
Fixed by e7dff73
